### ISSUE TITLE
A question from someone who likes the work here

### ISSUE THREAD

**Issue by rept0id** [dupontgu/pov_pong_mouse#2]
**_Hello !,_**

First of all, I want to say that **this is a very cool project**!

After that, I have a question :

I read in the documentation that the mouse is positioned using absolute coordinates, similar to how a touch screen operates. Given this, I’m curious: how does the mouse know the screen size ? My assumption is that with absolute positioning, you need to know the screen dimensions, especially if you want to make full use of the screen area. Of course, you could work with a fixed, small screen size and skip this headache.

I’m mostly interested in understanding how the implementation here determines or handles the actual screen size or if it just assumes a fixed "silver-bullet" size. All this, based that you work with absolute positioning.

**_Thank you !,_**
Rantouan
___

_Feel free to ask me for clarification if my question isn’t clear enough_

**Comment by dupontgu** [comment]
Hi! You can think of it like a "silver-bullet" size, but really, it works more like a percentage. The mouse sends values between 0 and 32767 for both the x and y coordinates, and the computer is responsible for mapping those to the size of the monitor before displaying the cursor. So it _should_ work on any computer, any monitor. Sending (0, 0) should render the mouse in the top left of the screen, (32767, 32767) should render the mouse in the bottom right.

The code fore this is here: https://github.com/dupontgu/pov_pong_mouse/blob/main/game_mouse.ino#L91
